"""T005-A/B contracts: stdlib offline checks and opt-in real local PostgreSQL 16.

No application imports, existing DSNs, repository mounts, pulls or installs.
"""
from __future__ import annotations

import ast
import asyncio
import contextlib
import hashlib
import importlib
import io
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import time
import types
import unittest
from unittest import mock
import uuid
import warnings

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
SENTINEL = "T005_SECRET_customer@example.invalid"
DOCKER_FALLBACK = Path(
    "C:/Users/marwan/AppData/Local/Programs/DockerDesktop/resources/bin/docker.exe"
)

# Independently specified eight-column predecessor, with all three observed keys.
PREDECESSOR = """
CREATE TABLE public.admin_users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    is_superuser BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP
);
INSERT INTO public.admin_users
    (username,email,password_hash,is_active,is_superuser,created_at,last_login)
VALUES
    ('test_alpha','alpha@example.invalid','sha256:synthetic-alpha',TRUE,FALSE,
     '2023-11-05 01:30:00',NULL),
    ('test_beta','beta@example.invalid','synthetic-beta',FALSE,TRUE,
     '2024-03-10 02:30:00','2024-11-03 01:30:00');
CREATE TABLE public.admin_sessions (
    id SERIAL PRIMARY KEY, user_id INTEGER REFERENCES public.admin_users(id),
    session_token VARCHAR(255) UNIQUE NOT NULL, expires_at TIMESTAMP NOT NULL
);
INSERT INTO public.admin_sessions (user_id,session_token,expires_at)
VALUES (1,'synthetic-session-alpha','2027-11-07 01:30:00'),
       (2,'synthetic-session-beta','2027-03-14 02:30:00');
CREATE TABLE public.bookings (
    id SERIAL PRIMARY KEY, call_sid VARCHAR(100), phone_number VARCHAR(50),
    client_name VARCHAR(255), client_email VARCHAR(255), accountant_name VARCHAR(255),
    appointment_time TIMESTAMP, client_type VARCHAR(50), language VARCHAR(10),
    status VARCHAR(50) DEFAULT 'confirmed', created_at TIMESTAMP,
    ms_booking_id VARCHAR(255), notes TEXT
);
INSERT INTO public.bookings
    (call_sid,phone_number,client_name,client_email,accountant_name,
     appointment_time,client_type,language,status,created_at,ms_booking_id,notes)
SELECT 'synthetic-call-' || n, '+12025550100', 'Synthetic ' || n,
       'synthetic@example.invalid', 'Synthetic consultant',
       TIMESTAMP '2024-11-03 01:30:00' + n * INTERVAL '1 day',
       'individual', 'ar', 'confirmed', TIMESTAMP '2024-03-10 02:30:00',
       'synthetic-provider-' || n, 'Invented fixture only'
FROM generate_series(1,16) AS n;
CREATE SEQUENCE public.unused_sequence START 81;
"""
LEDGER = """
CREATE TABLE public.schema_migrations (
    version TEXT PRIMARY KEY, checksum TEXT NOT NULL,
    applied_at TIMESTAMP WITH TIME ZONE NOT NULL
);
"""
BOOTSTRAP_SCHEMA_PATH = ROOT / "migrations/bootstrap_schema.sql"

# T005-B expectations come from the reviewed declarations and runtime SQL; no
# expectation is generated by parsing the schema asset under test.
APPLICATION_TABLE_COLUMNS = {
    "admin_sessions": ("id", "user_id", "session_token", "created_at", "expires_at",
                       "ip_address", "user_agent"),
    "admin_users": ("id", "username", "email", "password_hash", "is_active",
                    "is_superuser", "created_at", "updated_at", "last_login"),
    "analytics_events": ("id", "tenant_id", "call_sid", "event_type", "event_data",
                         "duration_ms", "timestamp"),
    "api_usage": ("id", "service_name", "request_count", "tokens_used",
                  "characters_used", "audio_seconds", "estimated_cost", "recorded_at"),
    "appointments": ("id", "call_sid", "tenant_id", "client_name", "client_phone",
                     "client_email", "accountant_name", "appointment_time",
                     "appointment_time_formatted", "client_type", "language", "status",
                     "booking_url", "event_type_uri", "service_id", "staff_id",
                     "ms_booking_id", "reminder_sent", "reminder_sent_at", "created_at",
                     "updated_at"),
    "bookings": ("id", "call_sid", "phone_number", "client_name", "client_email",
                 "accountant_name", "appointment_time", "client_type", "language",
                 "status", "created_at", "ms_booking_id", "notes"),
    "call_logs": ("id", "call_sid", "phone_number", "caller_name", "language",
                  "started_at", "ended_at", "duration_seconds", "status",
                  "transfer_requested", "dtmf_count", "booking_made", "notes"),
    "callers": ("id", "phone_number", "name", "language", "call_count", "first_call",
                "last_call", "tenant_id", "created_at", "updated_at"),
    "calls": ("id", "call_sid", "tenant_id", "phone_number", "caller_name", "language",
              "detected_language", "direction", "status", "started_at", "ended_at",
              "duration_seconds", "conversation_turns", "transferred", "transferred_to",
              "recording_url", "transcription", "error_message", "created_at", "updated_at"),
    "conversation_turns": ("id", "call_sid", "role", "content", "language",
                           "audio_duration_ms", "stt_confidence", "intent", "entities",
                           "timestamp"),
    "conversations": ("id", "call_sid", "tenant_id", "state", "intent_history",
                      "summary", "sentiment", "created_at", "updated_at"),
    "knowledge_articles": ("id", "tenant_id", "category", "question", "answer",
                           "language", "priority", "tags", "is_active", "created_at",
                           "updated_at"),
    "mfa_codes": ("id", "user_id", "code", "created_at", "expires_at", "used"),
    "sms_logs": ("id", "phone_number", "client_name", "message", "provider", "status",
                 "sent_at", "booking_id", "booking_link", "error_message"),
    "system_metrics": ("id", "cpu_percent", "memory_percent", "disk_percent",
                       "active_calls", "recorded_at"),
    "tenants": ("id", "name", "slug", "industry", "phone_number", "is_active",
                "settings", "created_at", "updated_at"),
    "users": ("id", "tenant_id", "username", "password_hash", "email", "role",
              "mfa_enabled", "mfa_secret", "last_login", "is_active", "created_at",
              "updated_at"),
}

EXPLICIT_SEQUENCES = {
    "analytics_events_id_seq", "appointments_id_seq", "callers_id_seq", "calls_id_seq",
    "conversation_turns_id_seq", "conversations_id_seq", "knowledge_articles_id_seq",
    "tenants_id_seq", "users_id_seq",
}
SERIAL_SEQUENCES = {
    "admin_sessions_id_seq", "admin_users_id_seq", "api_usage_id_seq",
    "bookings_id_seq", "call_logs_id_seq", "mfa_codes_id_seq", "sms_logs_id_seq",
    "system_metrics_id_seq",
}

SECONDARY_INDEXES = {
    "idx_admin_sessions_token": ("admin_sessions", ("session_token",)),
    "idx_analytics_tenant": ("analytics_events", ("tenant_id",)),
    "idx_analytics_timestamp": ("analytics_events", ("timestamp",)),
    "idx_analytics_type": ("analytics_events", ("event_type",)),
    "idx_appointments_phone": ("appointments", ("client_phone",)),
    "idx_appointments_status": ("appointments", ("status",)),
    "idx_appointments_time": ("appointments", ("appointment_time",)),
    "idx_bookings_accountant": ("bookings", ("accountant_name",)),
    "idx_bookings_appointment_time": ("bookings", ("appointment_time",)),
    "idx_call_logs_phone_number": ("call_logs", ("phone_number",)),
    "idx_call_logs_started_at": ("call_logs", ("started_at",)),
    "idx_callers_last_call": ("callers", ("last_call",)),
    "idx_callers_phone": ("callers", ("phone_number",)),
    "idx_callers_tenant": ("callers", ("tenant_id",)),
    "idx_calls_phone": ("calls", ("phone_number",)),
    "idx_calls_started": ("calls", ("started_at",)),
    "idx_calls_status": ("calls", ("status",)),
    "idx_calls_tenant": ("calls", ("tenant_id",)),
    "idx_conversations_call_sid": ("conversations", ("call_sid",)),
    "idx_knowledge_category": ("knowledge_articles", ("category",)),
    "idx_knowledge_language": ("knowledge_articles", ("language",)),
    "idx_knowledge_tenant": ("knowledge_articles", ("tenant_id",)),
    "idx_mfa_codes_user_expires": ("mfa_codes", ("user_id", "expires_at")),
    "idx_sms_logs_sent_at": ("sms_logs", ("sent_at",)),
    "idx_turns_call_sid": ("conversation_turns", ("call_sid",)),
    "idx_turns_timestamp": ("conversation_turns", ("timestamp",)),
}

UNIQUE_KEYS = {
    ("admin_sessions", ("session_token",)),
    ("admin_users", ("email",)),
    ("admin_users", ("username",)),
    ("api_usage", ("service_name", "recorded_at")),
    ("call_logs", ("call_sid",)),
    ("callers", ("phone_number",)),
    ("calls", ("call_sid",)),
    ("tenants", ("slug",)),
    ("users", ("username",)),
}
FOREIGN_KEYS = {
    ("admin_sessions", ("user_id",), "admin_users", ("id",), "c"),
    ("appointments", ("call_sid",), "calls", ("call_sid",), "n"),
    ("conversation_turns", ("call_sid",), "calls", ("call_sid",), "c"),
    ("conversations", ("call_sid",), "calls", ("call_sid",), "c"),
    ("mfa_codes", ("user_id",), "admin_users", ("id",), "c"),
    ("sms_logs", ("booking_id",), "bookings", ("id",), "a"),
}
TRIGGER_TARGETS = {
    "update_appointments_updated_at": "appointments",
    "update_callers_updated_at": "callers",
    "update_calls_updated_at": "calls",
    "update_conversations_updated_at": "conversations",
    "update_knowledge_updated_at": "knowledge_articles",
    "update_tenants_updated_at": "tenants",
    "update_users_updated_at": "users",
}

TIMESTAMP_TYPES = {
    ("admin_users", "created_at"): "timestamp without time zone",
    ("admin_users", "updated_at"): "timestamp without time zone",
    ("admin_users", "last_login"): "timestamp without time zone",
    ("mfa_codes", "created_at"): "timestamp without time zone",
    ("mfa_codes", "expires_at"): "timestamp without time zone",
    ("admin_sessions", "created_at"): "timestamp without time zone",
    ("admin_sessions", "expires_at"): "timestamp without time zone",
    ("call_logs", "started_at"): "timestamp without time zone",
    ("call_logs", "ended_at"): "timestamp without time zone",
    ("bookings", "appointment_time"): "timestamp without time zone",
    ("bookings", "created_at"): "timestamp without time zone",
    ("sms_logs", "sent_at"): "timestamp without time zone",
    ("system_metrics", "recorded_at"): "timestamp without time zone",
    ("calls", "started_at"): "timestamp with time zone",
    ("calls", "ended_at"): "timestamp with time zone",
    ("calls", "created_at"): "timestamp with time zone",
    ("calls", "updated_at"): "timestamp with time zone",
    ("conversations", "created_at"): "timestamp with time zone",
    ("conversations", "updated_at"): "timestamp with time zone",
    ("conversation_turns", "timestamp"): "timestamp with time zone",
    ("appointments", "appointment_time"): "timestamp with time zone",
    ("appointments", "reminder_sent_at"): "timestamp with time zone",
    ("appointments", "created_at"): "timestamp with time zone",
    ("appointments", "updated_at"): "timestamp with time zone",
    ("users", "last_login"): "timestamp with time zone",
    ("users", "created_at"): "timestamp with time zone",
    ("users", "updated_at"): "timestamp with time zone",
    ("tenants", "created_at"): "timestamp with time zone",
    ("tenants", "updated_at"): "timestamp with time zone",
    ("knowledge_articles", "created_at"): "timestamp with time zone",
    ("knowledge_articles", "updated_at"): "timestamp with time zone",
    ("callers", "first_call"): "timestamp with time zone",
    ("callers", "last_call"): "timestamp with time zone",
    ("callers", "created_at"): "timestamp with time zone",
    ("callers", "updated_at"): "timestamp with time zone",
    ("analytics_events", "timestamp"): "timestamp with time zone",
}

REQUIRED_COLUMNS = {
    *( (table, "id") for table in APPLICATION_TABLE_COLUMNS ),
    ("admin_sessions", "session_token"), ("admin_sessions", "expires_at"),
    ("admin_users", "username"), ("admin_users", "email"), ("admin_users", "password_hash"),
    ("analytics_events", "event_type"), ("api_usage", "service_name"),
    ("appointments", "client_name"), ("appointments", "client_phone"),
    ("appointments", "appointment_time"), ("callers", "phone_number"), ("callers", "name"),
    ("calls", "call_sid"), ("conversation_turns", "role"),
    ("conversation_turns", "content"), ("knowledge_articles", "question"),
    ("knowledge_articles", "answer"), ("mfa_codes", "code"), ("mfa_codes", "expires_at"),
    ("tenants", "name"), ("tenants", "slug"), ("users", "username"),
    ("users", "password_hash"),
}

DEFAULTED_COLUMNS = {
    "admin_sessions": ("id", "created_at"),
    "admin_users": ("id", "is_active", "is_superuser", "created_at", "updated_at"),
    "analytics_events": ("id", "tenant_id", "timestamp"),
    "api_usage": ("id", "request_count", "tokens_used", "characters_used",
                  "audio_seconds", "estimated_cost", "recorded_at"),
    "appointments": ("id", "tenant_id", "language", "status", "reminder_sent",
                     "created_at", "updated_at"),
    "bookings": ("id", "status", "created_at"),
    "call_logs": ("id", "started_at", "status", "transfer_requested", "dtmf_count",
                  "booking_made"),
    "callers": ("id", "language", "call_count", "first_call", "last_call", "tenant_id",
                "created_at", "updated_at"),
    "calls": ("id", "tenant_id", "language", "direction", "status", "started_at",
              "conversation_turns", "transferred", "created_at", "updated_at"),
    "conversation_turns": ("id", "language", "timestamp"),
    "conversations": ("id", "tenant_id", "created_at", "updated_at"),
    "knowledge_articles": ("id", "tenant_id", "language", "priority", "is_active",
                           "created_at", "updated_at"),
    "mfa_codes": ("id", "created_at", "used"),
    "sms_logs": ("id", "sent_at"),
    "system_metrics": ("id", "active_calls", "recorded_at"),
    "tenants": ("id", "is_active", "created_at", "updated_at"),
    "users": ("id", "tenant_id", "role", "mfa_enabled", "is_active", "created_at",
              "updated_at"),
}


def docker_call(executable, arguments, timeout=20):
    env = {k: v for k, v in os.environ.items() if not k.startswith("DOCKER_")}
    return subprocess.run(
        [executable, "--context", "desktop-linux", *arguments],
        env=env, capture_output=True, text=True, timeout=timeout, check=False,
    )


def docker_ok(executable, arguments, timeout=20):
    result = docker_call(executable, arguments, timeout)
    if result.returncode:
        raise RuntimeError("T005 local Docker prerequisite/command failed")
    return result.stdout


def cleanup(executable, candidates):
    """Visit every exact candidate even after an uncertain create/remove result."""
    errors = []
    for name in reversed(candidates):
        try:
            docker_call(executable, ["container", "rm", "--force", "--volumes", name])
            result = docker_call(executable, ["container", "inspect", name])
            if result.returncode and "no such" in result.stderr.lower():
                continue
        except (OSError, subprocess.TimeoutExpired):
            pass
        errors.append(name)
    return errors


def auth_password_statements():
    """Read both real UPDATE paths without importing live-client modules."""
    tree = ast.parse((ROOT / "services/dashboard/auth_service.py").read_text("utf-8"))
    return [
        node.value for node in ast.walk(tree)
        if isinstance(node, ast.Constant) and isinstance(node.value, str)
        and node.value.startswith("UPDATE admin_users SET password_hash")
    ]


class OfflineTests(unittest.TestCase):
    def setUp(self):
        self.runner = importlib.import_module("migrations.runner")

    def invoke(self, args):
        output = io.StringIO()
        with contextlib.redirect_stdout(output), contextlib.redirect_stderr(output):
            code = self.runner.main(args)
        return code, output.getvalue()

    def test_bootstrap_schema_is_explicit_plain_sql(self):
        sql = BOOTSTRAP_SCHEMA_PATH.read_text(encoding="utf-8")
        upper = sql.upper()
        self.assertNotIn("\\ECHO", upper)
        self.assertNotIn("IF NOT EXISTS", upper)
        self.assertNotIn("CREATE OR REPLACE", upper)
        self.assertNotIn("SCHEMA_MIGRATIONS", upper)
        self.assertNotRegex(upper, r"\b(BEGIN|COMMIT|ROLLBACK)\s*;")
        self.assertNotRegex(upper, r"\bCREATE\s+(EXTENSION|SCHEMA)\b")
        self.assertNotRegex(upper, r"\bINSERT\s+INTO\b")
        self.assertNotRegex(upper, r"\bSETVAL\s*\(")
        self.assertNotRegex(upper, r"\bSELECT\s+[^;]*\bNEXTVAL\s*\(")
        self.assertNotRegex(upper, r"\bREFERENCES\s+(?!PUBLIC\.)")
        self.assertNotRegex(
            upper,
            r"(?m)^CREATE\s+(?:TABLE|SEQUENCE|FUNCTION)\s+(?!PUBLIC\.)",
        )
        self.assertEqual(
            set(re.findall(r"(?im)^CREATE TABLE public\.([a-z_]+)\s*\(", sql)),
            set(APPLICATION_TABLE_COLUMNS),
        )
        self.assertEqual(len(re.findall(r"(?im)^CREATE SEQUENCE public\.", sql)), 9)
        self.assertEqual(len(re.findall(r"(?im)^CREATE INDEX ", sql)), 26)
        self.assertEqual(
            len(re.findall(r"(?im)^\s*BEFORE UPDATE ON public\.", sql)),
            7,
        )

    def test_missing_configuration_never_uses_application_url(self):
        with mock.patch.dict(os.environ, {"DATABASE_URL": SENTINEL}, clear=True), \
                mock.patch.object(self.runner, "_connect", new_callable=mock.AsyncMock) as connect:
            code, output = self.invoke(["--apply"])
        self.assertNotEqual(code, 0)
        self.assertIn("configuration", output)
        self.assertNotIn(SENTINEL, output)
        connect.assert_not_called()

    def test_cli_requires_exactly_one_mode_and_redacts_bad_arguments(self):
        for args in (
            [], ["--apply", "--status"], ["--apply", "--prepare"],
            ["--status", "--prepare"], ["--sql", SENTINEL], [SENTINEL],
        ):
            with self.subTest(args=args):
                code, output = self.invoke(args)
                self.assertNotEqual(code, 0)
                self.assertNotIn(SENTINEL, output)
                self.assertNotIn("Traceback", output)
        with self.assertRaisesRegex(self.runner.MigrationError, "choose exactly one"):
            asyncio.run(self.runner.run(apply=True, prepare=True))

    def test_connection_failure_redacts_driver_details(self):
        with mock.patch.dict(os.environ, {"MIGRATION_DATABASE_URL": SENTINEL}), \
                mock.patch.object(self.runner, "_connect", new_callable=mock.AsyncMock,
                                  side_effect=RuntimeError(SENTINEL)):
            code, output = self.invoke(["--status"])
        self.assertNotEqual(code, 0)
        self.assertIn("connection", output)
        self.assertNotIn(SENTINEL, output)
        self.assertNotIn("Traceback", output)

    def test_driver_connect_is_bounded_and_does_not_import_application(self):
        connect = mock.AsyncMock(return_value=object())
        with mock.patch.dict(sys.modules, {"asyncpg": types.SimpleNamespace(connect=connect)}):
            asyncio.run(self.runner._connect("postgresql://synthetic:invented@127.0.0.1:5432/t005"))
        self.assertGreater(connect.call_args.kwargs["timeout"], 0)
        self.assertLessEqual(connect.call_args.kwargs["timeout"], 15)
        self.assertLessEqual(connect.call_args.kwargs["command_timeout"], 30)
        # The runner itself must not import application modules (the full suite may).
        tree = ast.parse((ROOT / "migrations/runner.py").read_text("utf-8"))
        modules = [node.module for node in ast.walk(tree) if isinstance(node, ast.ImportFrom)]
        self.assertFalse(any(m and m.startswith(("config", "services")) for m in modules))

    def test_incomplete_url_never_inherits_database_or_credentials(self):
        connect = mock.AsyncMock()
        with mock.patch.dict(sys.modules, {"asyncpg": types.SimpleNamespace(connect=connect)}), \
                mock.patch.dict(os.environ, {"PGHOST": SENTINEL, "PGPASSWORD": SENTINEL,
                                            "PGDATABASE": SENTINEL}):
            for url in ("postgresql:///", "postgresql://user@localhost/test",
                        "postgresql://user:password@localhost", "invalid"):
                with self.subTest(url=url):
                    with self.assertRaisesRegex(self.runner.MigrationError, "configuration"):
                        asyncio.run(self.runner._connect(url))
        connect.assert_not_called()

    def test_exact_byte_manifest_and_auth_path_oracle(self):
        revision, = self.runner.MANIFEST
        self.assertEqual(revision, ("0001", "0001_admin_users_updated_at.sql"))
        sql, checksum = self.runner._load_revision()
        raw = (ROOT / "migrations" / revision[1]).read_bytes()
        self.assertEqual(checksum, hashlib.sha256(raw).hexdigest())
        self.assertEqual(sql, raw.decode("utf-8"))
        self.assertEqual(auth_password_statements(), [
            "UPDATE admin_users SET password_hash = $1, updated_at = NOW() WHERE id = $2"
        ] * 2)

    def test_prepare_assets_have_pinned_exact_byte_checksums(self):
        contract = importlib.import_module("migrations.schema_contract")
        _, revision_checksum = self.runner._load_revision()
        bootstrap_sql, bootstrap_checksum = self.runner._load_bootstrap()
        self.assertEqual(revision_checksum, contract.REVISION_CHECKSUM)
        self.assertEqual(bootstrap_checksum, contract.BOOTSTRAP_CHECKSUM)
        self.assertEqual(
            bootstrap_sql,
            (ROOT / "migrations/bootstrap_schema.sql").read_bytes().decode("utf-8"),
        )
        self.assertIn(
            "migrations/*.sql text eol=lf",
            (ROOT / ".gitattributes").read_text(encoding="utf-8").splitlines(),
        )

    def test_connection_closed_after_transaction_failure(self):
        conn = mock.Mock()
        conn.close = mock.AsyncMock()
        conn.transaction.side_effect = RuntimeError(SENTINEL)
        with mock.patch.dict(os.environ, {"MIGRATION_DATABASE_URL": SENTINEL}), \
                mock.patch.object(self.runner, "_connect", new_callable=mock.AsyncMock,
                                  return_value=conn):
            code, output = self.invoke(["--apply"])
        self.assertNotEqual(code, 0)
        self.assertNotIn(SENTINEL, output)
        conn.close.assert_awaited_once()

    def test_failed_close_terminates_connection_without_leaking_error(self):
        conn = mock.Mock()
        conn.close = mock.AsyncMock(side_effect=RuntimeError(SENTINEL))
        conn.transaction.side_effect = RuntimeError(SENTINEL)
        with mock.patch.dict(os.environ, {"MIGRATION_DATABASE_URL": SENTINEL}), \
                mock.patch.object(self.runner, "_connect", new_callable=mock.AsyncMock,
                                  return_value=conn):
            code, output = self.invoke(["--apply"])
        self.assertNotEqual(code, 0)
        self.assertNotIn(SENTINEL, output)
        conn.terminate.assert_called_once()

    def test_cleanup_continues_and_reports_exact_uncertain_resource(self):
        def fake(executable, arguments, timeout=20):
            if arguments[-1] == "t005-uncertain":
                raise subprocess.TimeoutExpired("docker", 20)
            return subprocess.CompletedProcess([], 1, "", "No such container")
        with mock.patch(__name__ + ".docker_call", side_effect=fake) as call:
            self.assertEqual(cleanup("docker", ["t005-absent", "t005-uncertain"]),
                             ["t005-uncertain"])
        self.assertEqual(call.call_count, 3)

    def test_docker_always_uses_explicit_context_and_strips_overrides(self):
        with mock.patch.dict(os.environ, {"DOCKER_HOST": SENTINEL}), \
                mock.patch("subprocess.run") as run:
            docker_call("docker", ["info"])
        self.assertEqual(run.call_args.args[0],
                         ["docker", "--context", "desktop-linux", "info"])
        self.assertNotIn("DOCKER_HOST", run.call_args.kwargs["env"])


@unittest.skipUnless(os.environ.get("T005_RUN_DOCKER_TESTS") == "1",
                     "real PostgreSQL requires T005_RUN_DOCKER_TESTS=1")
class PostgreSQLTests(unittest.IsolatedAsyncioTestCase):
    @classmethod
    def setUpClass(cls):
        cls.driver = importlib.import_module("asyncpg")
        cls.runner = importlib.import_module("migrations.runner")
        cls.docker = shutil.which("docker")
        if cls.docker is None and DOCKER_FALLBACK.is_file():
            cls.docker = str(DOCKER_FALLBACK)
        if cls.docker is None:
            raise RuntimeError("T005 requires existing local Docker; no installation attempted")
        details = json.loads(docker_ok(cls.docker, ["context", "inspect", "desktop-linux"]))
        endpoint = details[0]["Endpoints"]["docker"]["Host"]
        if not (endpoint.startswith("npipe:////./pipe/") or endpoint.startswith("unix:///")):
            raise RuntimeError("T005 desktop-linux endpoint is not a local socket")
        if docker_ok(cls.docker, ["info", "--format", "{{.OSType}}"]).strip() != "linux":
            raise RuntimeError("T005 requires local Linux Docker")
        listing = docker_ok(cls.docker, ["image", "ls", "--format", "{{json .}}"])
        candidates = [json.loads(line) for line in listing.splitlines() if line]
        images = sorted({row["Repository"] + ":" + row["Tag"] for row in candidates
                         if row["Repository"] in ("postgres", "docker.io/library/postgres")
                         and re.fullmatch(r"16(?:\.\d+)?(?:-[a-z0-9.-]+)?", row["Tag"])})
        if not images:
            raise RuntimeError("T005 requires an existing official PostgreSQL 16 image; no pull")
        image = json.loads(docker_ok(cls.docker, ["image", "inspect", images[0]]))[0]
        if "PG_MAJOR=16" not in image["Config"]["Env"]:
            raise RuntimeError("T005 local image does not declare PostgreSQL 16")
        cls.name = "t005-migrations-" + uuid.uuid4().hex
        cls.database = "t005_" + uuid.uuid4().hex
        cls.candidates = []
        try:
            cls.candidates.append(cls.name)  # Track before uncertain dispatch.
            docker_ok(cls.docker, [
                "create", "--pull", "never", "--name", cls.name,
                "--memory", "192m", "--memory-swap", "192m", "--cpus", "0.5",
                "--pids-limit", "128", "--shm-size", "32m", "--network", "bridge",
                "--publish", "127.0.0.1::5432",
                "--tmpfs", "/var/lib/postgresql/data:rw,noexec,nosuid,size=128m",
                "--env", "PGDATA=/var/lib/postgresql/data/pgdata",
                "--env", "POSTGRES_USER=t005", "--env", "POSTGRES_PASSWORD=t005-synthetic",
                "--env", "POSTGRES_DB=" + cls.database, image["Id"],
                "-c", "shared_buffers=16MB", "-c", "max_connections=12",
                "-c", "work_mem=1MB", "-c", "maintenance_work_mem=16MB",
            ], timeout=30)
            docker_ok(cls.docker, ["start", cls.name], timeout=30)
            ports = json.loads(docker_ok(cls.docker, [
                "inspect", "--format", "{{json .NetworkSettings.Ports}}", cls.name]))
            binding, = ports["5432/tcp"]
            if binding["HostIp"] != "127.0.0.1":
                raise RuntimeError("T005 port is not loopback-only")
            cls.dsn = ("postgresql://t005:t005-synthetic@127.0.0.1:"
                       + str(int(binding["HostPort"])) + "/" + cls.database)
            deadline = time.monotonic() + 45
            while time.monotonic() < deadline:
                result = docker_call(cls.docker, ["exec", cls.name, "pg_isready",
                                                 "-h", "127.0.0.1", "-U", "t005", "-d", cls.database], 5)
                if result.returncode == 0:
                    break
                time.sleep(0.25)
            else:
                raise RuntimeError("T005 isolated PostgreSQL startup timed out")
        except BaseException:
            errors = cleanup(cls.docker, cls.candidates)
            if errors:
                warnings.warn("T005 cleanup unconfirmed: " + ", ".join(errors), RuntimeWarning)
            raise

    @classmethod
    def tearDownClass(cls):
        errors = cleanup(cls.docker, cls.candidates)
        if errors:
            raise AssertionError("T005 cleanup unconfirmed: " + ", ".join(errors))
        print("T005 cleanup confirmed: " + cls.name)

    async def asyncSetUp(self):
        self.conn = await self.driver.connect(self.dsn, timeout=10, command_timeout=15)
        self.addAsyncCleanup(self.conn.close)
        self.assertTrue(160000 <= int(await self.conn.fetchval("SHOW server_version_num")) < 170000)
        await self.conn.execute("DROP SCHEMA public CASCADE; CREATE SCHEMA public;")
        await self.conn.execute(PREDECESSOR)

    async def migrate(self, apply=True):
        with mock.patch.dict(os.environ, {"MIGRATION_DATABASE_URL": self.dsn}):
            return await self.runner.run(apply=apply)

    async def prepare(self):
        with mock.patch.dict(os.environ, {"MIGRATION_DATABASE_URL": self.dsn}):
            return await self.runner.run(prepare=True)

    async def reset_public(self):
        await self.conn.execute("DROP SCHEMA public CASCADE; CREATE SCHEMA public")

    async def bootstrap(self):
        sql = BOOTSTRAP_SCHEMA_PATH.read_text(encoding="utf-8")
        async with self.conn.transaction():
            await self.conn.execute("SET LOCAL search_path = pg_catalog")
            await self.conn.execute(sql)

    async def test_prepare_empty_schema_is_atomic_idempotent_and_read_only_compatible(self):
        contract = importlib.import_module("migrations.schema_contract")
        await self.reset_public()
        self.assertEqual(await self.prepare(), "prepared bootstrap-v1 0001")
        tables = await self.conn.fetchval(
            "SELECT count(*) FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n "
            "ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind='r'")
        self.assertEqual(tables, 18)
        history = await self.conn.fetch(
            "SELECT version,checksum,applied_at FROM public.schema_migrations ORDER BY version")
        self.assertEqual(
            [(row["version"], row["checksum"]) for row in history],
            [("0001", contract.REVISION_CHECKSUM),
             ("bootstrap-v1", contract.BOOTSTRAP_CHECKSUM)],
        )
        self.assertTrue(all(row["applied_at"].tzinfo is not None for row in history))
        for table in APPLICATION_TABLE_COLUMNS:
            self.assertEqual(
                await self.conn.fetchval(f'SELECT count(*) FROM public."{table}"'), 0)
        before = await self.snapshot()
        async with self.conn.transaction(isolation="repeatable_read", readonly=True):
            await contract.check_runtime_compatibility(self.conn)
        self.assertEqual(await self.snapshot(), before)
        self.assertEqual(await self.prepare(), "up-to-date 0001")
        self.assertEqual(await self.snapshot(), before)
        self.assertEqual(await self.migrate(False), "up-to-date 0001")
        self.assertEqual(await self.migrate(), "up-to-date 0001")
        self.assertEqual(await self.snapshot(), before)

    async def test_prepare_complete_eight_column_family_preserves_rows_and_sequences(self):
        await self.reset_public()
        # Model an originally absent column, not a dropped-column catalog artifact.
        sql = BOOTSTRAP_SCHEMA_PATH.read_text(encoding="utf-8")
        column = "    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n"
        self.assertEqual(sql.count(column), 1)
        await self.conn.execute(sql.replace(column, ""))
        await self.conn.execute("""
            INSERT INTO public.admin_users
                (username,email,password_hash,created_at,last_login)
            VALUES ('legacy','legacy@example.invalid','synthetic',
                    '2023-11-05 01:30:00','2024-11-03 01:30:00');
            INSERT INTO public.admin_sessions
                (user_id,session_token,created_at,expires_at)
            VALUES (1,'synthetic-session','2023-11-05 01:30:00','2027-11-07 01:30:00');
            INSERT INTO public.bookings
                (call_sid,appointment_time,created_at,notes)
            SELECT 'synthetic-' || n, TIMESTAMP '2024-11-03 01:30:00' + n * INTERVAL '1 day',
                   TIMESTAMP '2024-03-10 02:30:00', 'invented'
            FROM generate_series(1,16) n;
            SELECT pg_catalog.setval('public.bookings_id_seq',81,true);
        """)
        before = await self.snapshot()
        self.assertEqual(await self.prepare(), "applied 0001")
        after = await self.snapshot()
        self.assertEqual(before["sequences"], after["sequences"])
        self.assertEqual(before["rows"]["bookings"], after["rows"]["bookings"])
        self.assertEqual(before["rows"]["admin_sessions"], after["rows"]["admin_sessions"])
        old_admin = [json.loads(row["row"]) for row in before["rows"]["admin_users"]]
        new_admin = [json.loads(row["row"]) for row in after["rows"]["admin_users"]]
        self.assertEqual(new_admin, [dict(row, updated_at=None) for row in old_admin])
        history = await self.conn.fetch(
            "SELECT version FROM public.schema_migrations ORDER BY version")
        self.assertEqual([row["version"] for row in history], ["0001"])

    async def test_prepare_rejects_partial_or_unknown_empty_path_without_mutation(self):
        for sql in (
            "CREATE TABLE public.calls (id integer)",
            "CREATE SEQUENCE public.unexpected_sequence",
            "CREATE DOMAIN public.unexpected_domain AS text",
            "CREATE TYPE public.unexpected_composite AS (marker text)",
        ):
            with self.subTest(sql=sql):
                await self.reset_public()
                await self.conn.execute(sql)
                before = await self.snapshot()
                with self.assertRaisesRegex(self.runner.MigrationError, "incompatible schema"):
                    await self.prepare()
                self.assertEqual(await self.snapshot(), before)

    async def test_prepare_rejects_full_contract_and_history_drift_without_mutation(self):
        cases = (
            "ALTER TABLE public.calls ALTER tenant_id TYPE bigint",
            "ALTER TABLE public.calls DROP CONSTRAINT calls_call_sid_key CASCADE",
            LEDGER + "INSERT INTO public.schema_migrations "
            "VALUES ('unknown','redacted',CURRENT_TIMESTAMP)",
            LEDGER + "INSERT INTO public.schema_migrations "
            "VALUES ('0001','wrong',CURRENT_TIMESTAMP)",
        )
        for sql in cases:
            with self.subTest(sql=sql[:45]):
                await self.reset_public()
                await self.bootstrap()
                await self.conn.execute(sql)
                before = await self.snapshot()
                with self.assertRaises(self.runner.MigrationError):
                    await self.prepare()
                self.assertEqual(await self.snapshot(), before)

        await self.reset_public()
        await self.prepare()
        for sql in (
            "UPDATE public.schema_migrations SET checksum='wrong' "
            "WHERE version='bootstrap-v1'",
            "DELETE FROM public.schema_migrations WHERE version='0001'",
        ):
            with self.subTest(history_sql=sql):
                if "DELETE" in sql:
                    await self.reset_public()
                    await self.prepare()
                await self.conn.execute(sql)
                before = await self.snapshot()
                with self.assertRaises(self.runner.MigrationError):
                    await self.prepare()
                self.assertEqual(await self.snapshot(), before)

    async def test_narrow_apply_fixture_never_passes_runtime_contract(self):
        contract = importlib.import_module("migrations.schema_contract")
        self.assertEqual(await self.migrate(), "applied 0001")
        before = await self.snapshot()
        async with self.conn.transaction(isolation="repeatable_read", readonly=True):
            with self.assertRaisesRegex(
                contract.SchemaCompatibilityError, "incompatible schema"
            ):
                await contract.check_runtime_compatibility(self.conn)
        self.assertEqual(await self.snapshot(), before)

    async def test_prepare_failure_after_bootstrap_rolls_back_and_retries(self):
        await self.reset_public()
        original = self.runner._record_revision
        reached = {"bootstrap": False}

        async def fail_after_bootstrap(conn, version, checksum):
            if version == "bootstrap-v1":
                reached["bootstrap"] = True
                raise RuntimeError(SENTINEL)
            return await original(conn, version, checksum)

        with mock.patch.object(self.runner, "_record_revision", side_effect=fail_after_bootstrap):
            with self.assertRaisesRegex(self.runner.MigrationError, "migration failed"):
                await self.prepare()
        self.assertTrue(reached["bootstrap"])
        self.assertFalse(await self.conn.fetchval(
            "SELECT EXISTS (SELECT 1 FROM pg_catalog.pg_class c "
            "JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace "
            "WHERE n.nspname='public' AND c.relkind IN ('r','S'))"))
        self.assertEqual(await self.prepare(), "prepared bootstrap-v1 0001")

    async def test_runtime_rejects_admin_drift_and_cross_schema_foreign_key(self):
        contract = importlib.import_module("migrations.schema_contract")
        await self.reset_public()
        await self.prepare()
        await self.conn.execute(
            "ALTER TABLE public.admin_users ALTER updated_at SET DEFAULT clock_timestamp()")
        async with self.conn.transaction(readonly=True):
            with self.assertRaises(contract.SchemaCompatibilityError):
                await contract.check_runtime_compatibility(self.conn)
        await self.conn.execute(
            "ALTER TABLE public.admin_users ALTER updated_at SET DEFAULT CURRENT_TIMESTAMP")
        await self.conn.execute("CREATE SCHEMA t005_other")
        try:
            await self.conn.execute("""
                CREATE TABLE t005_other.admin_users (id integer PRIMARY KEY);
                ALTER TABLE public.admin_sessions DROP CONSTRAINT admin_sessions_user_id_fkey;
                ALTER TABLE public.admin_sessions ADD FOREIGN KEY (user_id)
                  REFERENCES t005_other.admin_users(id) ON DELETE CASCADE;
            """)
            before = await self.snapshot()
            with self.assertRaises(self.runner.MigrationError):
                await self.prepare()
            async with self.conn.transaction(readonly=True):
                with self.assertRaises(contract.SchemaCompatibilityError):
                    await contract.check_runtime_compatibility(self.conn)
            self.assertEqual(await self.snapshot(), before)
        finally:
            await self.conn.execute("DROP SCHEMA t005_other CASCADE")

    async def test_actual_application_startup_and_readiness_against_postgresql(self):
        import httpx
        import pytest
        from test_database_startup import _load_main

        await self.reset_public()
        await self.prepare()
        before = await self.snapshot()
        events = []
        with pytest.MonkeyPatch.context() as patch:
            module, state = _load_main(patch, events, database_url=self.dsn)
            database = state["database"]
            async with module.lifespan(module.app):
                async with httpx.AsyncClient(
                    transport=httpx.ASGITransport(app=module.app),
                    base_url="http://testserver",
                ) as client:
                    self.assertEqual((await client.get("/ready")).status_code, 200)
                    self.assertEqual(await self.snapshot(), before)
                    await self.conn.execute("DROP TABLE public.calls CASCADE")
                    response = await client.get("/ready")
                    self.assertEqual(response.status_code, 503)
                    self.assertEqual(response.json(), {"status": "unavailable"})
                    self.assertEqual((await client.get("/health")).status_code, 200)
                    await database.close_db_pool()
                    self.assertEqual((await client.get("/ready")).status_code, 503)
            self.assertIsNone(database._pool)
            self.assertFalse(module.app.state.ready)
            self.assertEqual(events, ["scheduler-start", "tts-prewarm", "scheduler-stop"])

            events.clear()
            with self.assertRaises(database.DatabaseReadinessError) as error:
                async with module.lifespan(module.app):
                    self.fail("incompatible database started the app")
            self.assertEqual(str(error.exception), "database unavailable")
            self.assertEqual(events, [])
            self.assertIsNone(database._pool)
            self.assertFalse(module.app.state.ready)

    async def test_concurrent_prepare_serializes_initialization(self):
        await self.reset_public()
        with mock.patch.dict(os.environ, {"MIGRATION_DATABASE_URL": self.dsn}):
            results = await asyncio.gather(
                self.runner.run(prepare=True), self.runner.run(prepare=True),
                return_exceptions=True,
            )
        successes = [result for result in results if isinstance(result, str)]
        failures = [result for result in results if isinstance(result, Exception)]
        self.assertGreaterEqual(len(successes), 1)
        self.assertTrue(all(
            str(result) == "busy" for result in failures
        ))
        self.assertEqual(await self.prepare(), "up-to-date 0001")

    async def snapshot(self):
        # Complete synthetic row values and sequence states; no sequence calls.
        schema = await self.conn.fetch("""
            SELECT c.relname,c.relkind,a.attnum,a.attname,
                   pg_catalog.format_type(a.atttypid,a.atttypmod) AS type,
                   a.attnotnull,a.attidentity,a.attgenerated,
                   pg_catalog.pg_get_expr(d.adbin,d.adrelid) AS default_expr
            FROM pg_catalog.pg_class c
            JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace
            LEFT JOIN pg_catalog.pg_attribute a ON a.attrelid=c.oid AND a.attnum>0
            LEFT JOIN pg_catalog.pg_attrdef d ON d.adrelid=c.oid AND d.adnum=a.attnum
            WHERE n.nspname='public' ORDER BY c.relname,a.attnum
        """)
        keys = await self.conn.fetch("""
            SELECT conrelid::regclass::text,conname,pg_get_constraintdef(oid)
            FROM pg_constraint WHERE connamespace='public'::regnamespace ORDER BY 1,2
        """)
        indexes = await self.conn.fetch("SELECT indexname,indexdef FROM pg_indexes "
                                        "WHERE schemaname='public' ORDER BY indexname")
        triggers = await self.conn.fetch("""
            SELECT tgname,pg_get_triggerdef(t.oid) FROM pg_trigger t
            JOIN pg_class c ON c.oid=t.tgrelid
            WHERE c.relnamespace='public'::regnamespace ORDER BY tgname
        """)
        tables = await self.conn.fetch("SELECT tablename FROM pg_tables "
                                       "WHERE schemaname='public' ORDER BY tablename")
        rows = {}
        for table in tables:
            name = table["tablename"].replace('"', '""')
            rows[name] = await self.conn.fetch(
                f'SELECT row_to_json(t)::text AS row FROM public."{name}" t ORDER BY 1')
        sequences = {}
        for seq in await self.conn.fetch("SELECT sequencename FROM pg_sequences "
                                          "WHERE schemaname='public' ORDER BY sequencename"):
            name = seq["sequencename"].replace('"', '""')
            sequences[name] = await self.conn.fetchrow(
                f'SELECT last_value,is_called FROM public."{name}"')
        return dict(schema=schema,keys=keys,indexes=indexes,triggers=triggers,
                    rows=rows,sequences=sequences)

    async def test_bootstrap_creates_exact_empty_compatibility_schema(self):
        await self.reset_public()
        await self.bootstrap()

        rows = await self.conn.fetch("""
            SELECT table_name,column_name,ordinal_position,data_type,
                   character_maximum_length,is_nullable,column_default
            FROM information_schema.columns
            WHERE table_schema='public'
            ORDER BY table_name,ordinal_position
        """)
        columns = {}
        by_key = {}
        for row in rows:
            columns.setdefault(row["table_name"], []).append(row["column_name"])
            by_key[(row["table_name"], row["column_name"])] = row
        self.assertEqual({name: tuple(names) for name, names in columns.items()},
                         APPLICATION_TABLE_COLUMNS)
        self.assertIsNone(await self.conn.fetchval(
            "SELECT pg_catalog.to_regclass('public.schema_migrations')"))
        for table in APPLICATION_TABLE_COLUMNS:
            self.assertEqual(
                await self.conn.fetchval(f'SELECT count(*) FROM public."{table}"'), 0)

        actual_required = {
            key for key, row in by_key.items() if row["is_nullable"] == "NO"
        }
        self.assertEqual(actual_required, REQUIRED_COLUMNS)
        actual_defaulted = {
            key for key, row in by_key.items() if row["column_default"] is not None
        }
        expected_defaulted = {
            (table, column)
            for table, names in DEFAULTED_COLUMNS.items()
            for column in names
        }
        self.assertEqual(actual_defaulted, expected_defaulted)
        for key, expected_type in TIMESTAMP_TYPES.items():
            self.assertEqual(by_key[key]["data_type"], expected_type, key)

        lengths = {
            ("admin_sessions", "session_token"): 255,
            ("admin_users", "username"): 100,
            ("admin_users", "email"): 255,
            ("admin_users", "password_hash"): 255,
            ("appointments", "client_name"): 100,
            ("appointments", "client_phone"): 50,
            ("bookings", "client_name"): 255,
            ("call_logs", "call_sid"): 100,
            ("callers", "phone_number"): 50,
            ("calls", "call_sid"): 100,
            ("mfa_codes", "code"): 6,
            ("sms_logs", "booking_link"): 500,
            ("users", "username"): 50,
        }
        for key, expected_length in lengths.items():
            self.assertEqual(by_key[key]["character_maximum_length"], expected_length, key)
        for key in (("admin_users", "created_at"), ("admin_users", "updated_at"),
                    ("bookings", "created_at"), ("callers", "updated_at"),
                    ("appointments", "updated_at")):
            self.assertIn(by_key[key]["column_default"], ("CURRENT_TIMESTAMP", "now()"), key)
        self.assertEqual(by_key[("api_usage", "recorded_at")]["column_default"],
                         "CURRENT_DATE")
        self.assertTrue(by_key[("bookings", "status")]["column_default"].startswith(
            "'confirmed'"))
        self.assertTrue(by_key[("calls", "direction")]["column_default"].startswith(
            "'inbound'"))

        constraints = await self.conn.fetch("""
            SELECT source.relname AS source_table,c.contype::text,
                   ARRAY(SELECT a.attname::text
                         FROM pg_catalog.unnest(c.conkey) WITH ORDINALITY AS k(num,ord)
                         JOIN pg_catalog.pg_attribute a
                           ON a.attrelid=c.conrelid AND a.attnum=k.num
                         ORDER BY k.ord) AS source_columns,
                   target.relname AS target_table,
                   ARRAY(SELECT a.attname::text
                         FROM pg_catalog.unnest(c.confkey) WITH ORDINALITY AS k(num,ord)
                         JOIN pg_catalog.pg_attribute a
                           ON a.attrelid=c.confrelid AND a.attnum=k.num
                         ORDER BY k.ord) AS target_columns,
                   c.confdeltype::text,c.condeferrable,c.condeferred,c.convalidated
            FROM pg_catalog.pg_constraint c
            JOIN pg_catalog.pg_class source ON source.oid=c.conrelid
            LEFT JOIN pg_catalog.pg_class target ON target.oid=c.confrelid
            WHERE c.connamespace='public'::pg_catalog.regnamespace
        """)
        self.assertTrue(all(
            not row["condeferrable"] and not row["condeferred"] and row["convalidated"]
            for row in constraints
        ))
        primary = {
            row["source_table"] for row in constraints if row["contype"] == "p"
        }
        unique = {
            (row["source_table"], tuple(row["source_columns"]))
            for row in constraints if row["contype"] == "u"
        }
        foreign = {
            (row["source_table"], tuple(row["source_columns"]), row["target_table"],
             tuple(row["target_columns"]), row["confdeltype"])
            for row in constraints if row["contype"] == "f"
        }
        self.assertEqual(primary, set(APPLICATION_TABLE_COLUMNS))
        self.assertEqual(unique, UNIQUE_KEYS)
        self.assertEqual(foreign, FOREIGN_KEYS)
        self.assertEqual(len(constraints), 32)

        indexes = await self.conn.fetch("""
            SELECT index_class.relname AS index_name,table_class.relname AS table_name,
                   ARRAY(SELECT a.attname::text
                         FROM pg_catalog.unnest(i.indkey) WITH ORDINALITY AS k(num,ord)
                         JOIN pg_catalog.pg_attribute a
                           ON a.attrelid=i.indrelid AND a.attnum=k.num
                         WHERE k.ord <= i.indnkeyatts ORDER BY k.ord) AS columns,
                   i.indisunique,i.indisprimary,i.indisvalid,i.indisready,
                   i.indexprs IS NOT NULL AS expression,
                   i.indpred IS NOT NULL AS predicate
            FROM pg_catalog.pg_index i
            JOIN pg_catalog.pg_class index_class ON index_class.oid=i.indexrelid
            JOIN pg_catalog.pg_class table_class ON table_class.oid=i.indrelid
            WHERE table_class.relnamespace='public'::pg_catalog.regnamespace
              AND NOT EXISTS (
                  SELECT 1 FROM pg_catalog.pg_constraint c
                  WHERE c.conindid=i.indexrelid
              )
        """)
        self.assertTrue(all(
            not row["indisunique"] and not row["indisprimary"]
            and row["indisvalid"] and row["indisready"]
            and not row["expression"] and not row["predicate"]
            for row in indexes
        ))
        actual_indexes = {
            row["index_name"]: (row["table_name"], tuple(row["columns"]))
            for row in indexes
        }
        self.assertEqual(actual_indexes, SECONDARY_INDEXES)

        sequences = await self.conn.fetch("""
            SELECT sequence.relname AS sequence_name,owner_table.relname AS owner_table,
                   owner_column.attname AS owner_column
            FROM pg_catalog.pg_class sequence
            LEFT JOIN pg_catalog.pg_depend dependency
              ON dependency.classid='pg_catalog.pg_class'::pg_catalog.regclass
             AND dependency.objid=sequence.oid AND dependency.deptype='a'
            LEFT JOIN pg_catalog.pg_class owner_table
              ON owner_table.oid=dependency.refobjid
            LEFT JOIN pg_catalog.pg_attribute owner_column
              ON owner_column.attrelid=dependency.refobjid
             AND owner_column.attnum=dependency.refobjsubid
            WHERE sequence.relnamespace='public'::pg_catalog.regnamespace
              AND sequence.relkind='S'
        """)
        self.assertEqual({row["sequence_name"] for row in sequences},
                         EXPLICIT_SEQUENCES | SERIAL_SEQUENCES)
        ownership = {
            row["sequence_name"]: (row["owner_table"], row["owner_column"])
            for row in sequences
        }
        for sequence in EXPLICIT_SEQUENCES:
            self.assertEqual(ownership[sequence], (None, None))
        for sequence in SERIAL_SEQUENCES:
            table = sequence.removesuffix("_id_seq")
            self.assertEqual(ownership[sequence], (table, "id"))
        bindings = await self.conn.fetch("""
            SELECT table_class.relname AS table_name,
                   sequence_class.relname AS sequence_name
            FROM pg_catalog.pg_attrdef default_value
            JOIN pg_catalog.pg_class table_class
              ON table_class.oid=default_value.adrelid
            JOIN pg_catalog.pg_attribute column_value
              ON column_value.attrelid=default_value.adrelid
             AND column_value.attnum=default_value.adnum
            JOIN pg_catalog.pg_depend dependency
              ON dependency.classid='pg_catalog.pg_attrdef'::pg_catalog.regclass
             AND dependency.objid=default_value.oid
             AND dependency.refclassid='pg_catalog.pg_class'::pg_catalog.regclass
            JOIN pg_catalog.pg_class sequence_class
              ON sequence_class.oid=dependency.refobjid
             AND sequence_class.relkind='S'
            WHERE table_class.relnamespace='public'::pg_catalog.regnamespace
              AND column_value.attname='id'
        """)
        self.assertEqual(
            {(row["table_name"], row["sequence_name"]) for row in bindings},
            {(table, table + "_id_seq") for table in APPLICATION_TABLE_COLUMNS},
        )

        triggers = await self.conn.fetch("""
            SELECT trigger_name,event_object_table,action_timing,event_manipulation,
                   action_orientation
            FROM information_schema.triggers
            WHERE trigger_schema='public'
        """)
        self.assertEqual(
            {row["trigger_name"]: row["event_object_table"] for row in triggers},
            TRIGGER_TARGETS,
        )
        self.assertTrue(all(
            row["action_timing"] == "BEFORE"
            and row["event_manipulation"] == "UPDATE"
            and row["action_orientation"] == "ROW"
            for row in triggers
        ))
        functions = await self.conn.fetch("""
            SELECT p.proname,l.lanname
            FROM pg_catalog.pg_proc p
            JOIN pg_catalog.pg_language l ON l.oid=p.prolang
            WHERE p.pronamespace='public'::pg_catalog.regnamespace
        """)
        self.assertEqual([(row["proname"], row["lanname"]) for row in functions],
                         [("update_updated_at_column", "plpgsql")])

    async def test_bootstrap_supports_runtime_sql_and_declared_keys(self):
        await self.reset_public()
        await self.bootstrap()

        admin_id = await self.conn.fetchval("""
            INSERT INTO public.admin_users (username,email,password_hash)
            VALUES ('synthetic-admin','admin@example.invalid','synthetic-hash')
            RETURNING id
        """)
        mfa_id = await self.conn.fetchval("""
            INSERT INTO public.mfa_codes (user_id,code,expires_at)
            VALUES ($1,'123456',TIMESTAMP '2030-01-01 00:00:00') RETURNING id
        """, admin_id)
        session_id = await self.conn.fetchval("""
            INSERT INTO public.admin_sessions (user_id,session_token,expires_at)
            VALUES ($1,'synthetic-session',TIMESTAMP '2030-01-01 00:00:00') RETURNING id
        """, admin_id)
        for statement in auth_password_statements():
            self.assertEqual(
                await self.conn.execute(statement, "synthetic-updated-hash", admin_id),
                "UPDATE 1",
            )
        admin = await self.conn.fetchrow(
            "SELECT * FROM public.admin_users WHERE id=$1", admin_id)
        self.assertEqual(admin["password_hash"], "synthetic-updated-hash")
        self.assertIsNotNone(admin["updated_at"])
        self.assertTrue(admin["is_active"])
        self.assertFalse(admin["is_superuser"])
        with self.assertRaises(self.driver.UniqueViolationError):
            await self.conn.execute("""
                INSERT INTO public.admin_users (username,email,password_hash)
                VALUES ('synthetic-admin','other@example.invalid','synthetic-hash')
            """)
        await self.conn.execute("DELETE FROM public.admin_users WHERE id=$1", admin_id)
        self.assertEqual(await self.conn.fetchval(
            "SELECT count(*) FROM public.mfa_codes WHERE id=$1", mfa_id), 0)
        self.assertEqual(await self.conn.fetchval(
            "SELECT count(*) FROM public.admin_sessions WHERE id=$1", session_id), 0)

        call_id = await self.conn.fetchval("""
            INSERT INTO public.calls (call_sid,phone_number,caller_name)
            VALUES ('synthetic-call-runtime','+12025550111','Synthetic caller')
            RETURNING id
        """)
        conversation_id = await self.conn.fetchval("""
            INSERT INTO public.conversations (call_sid,state)
            VALUES ('synthetic-call-runtime','{"state":"synthetic"}'::jsonb) RETURNING id
        """)
        turn_id = await self.conn.fetchval("""
            INSERT INTO public.conversation_turns (call_sid,role,content)
            VALUES ('synthetic-call-runtime','user','Synthetic content') RETURNING id
        """)
        appointment_id = await self.conn.fetchval("""
            INSERT INTO public.appointments
                (call_sid,client_name,client_phone,appointment_time)
            VALUES
                ('synthetic-call-runtime','Synthetic client','+12025550112',
                 TIMESTAMPTZ '2028-01-15 14:00:00+00')
            RETURNING id
        """)
        with self.assertRaises(self.driver.UniqueViolationError):
            await self.conn.execute(
                "INSERT INTO public.calls (call_sid) VALUES ('synthetic-call-runtime')")
        call_defaults = await self.conn.fetchrow(
            "SELECT tenant_id,language,direction,status,conversation_turns,transferred "
            "FROM public.calls WHERE id=$1", call_id)
        self.assertEqual(tuple(call_defaults), (1, "en", "inbound", "in_progress", 0, False))
        await self.conn.execute("DELETE FROM public.calls WHERE id=$1", call_id)
        self.assertEqual(await self.conn.fetchval(
            "SELECT count(*) FROM public.conversations WHERE id=$1", conversation_id), 0)
        self.assertEqual(await self.conn.fetchval(
            "SELECT count(*) FROM public.conversation_turns WHERE id=$1", turn_id), 0)
        self.assertIsNone(await self.conn.fetchval(
            "SELECT call_sid FROM public.appointments WHERE id=$1", appointment_id))

        caller_id = await self.conn.fetchval("""
            INSERT INTO public.callers (phone_number,name)
            VALUES ('+12025550113','Synthetic caller profile') RETURNING id
        """)
        call_log_id = await self.conn.fetchval("""
            INSERT INTO public.call_logs
                (call_sid,phone_number,caller_name,language)
            VALUES ('synthetic-log','+12025550114','Synthetic log caller','ar')
            RETURNING id
        """)
        booking_id = await self.conn.fetchval("""
            INSERT INTO public.bookings
                (call_sid,phone_number,client_name,client_email,accountant_name,
                 appointment_time,client_type,language,ms_booking_id,notes)
            VALUES
                ('synthetic-booking-call','+12025550115','Synthetic booking',
                 'booking@example.invalid','Synthetic consultant',
                 TIMESTAMP '2028-02-01 09:30:00','individual','en',
                 'synthetic-provider-id','Synthetic note')
            RETURNING id
        """)
        sms_id = await self.conn.fetchval("""
            INSERT INTO public.sms_logs
                (phone_number,client_name,message,provider,status,booking_id,booking_link)
            VALUES
                ('+12025550115','Synthetic booking','Synthetic message',
                 'synthetic-provider','sent',$1,'https://example.invalid/synthetic')
            RETURNING id
        """, booking_id)
        with self.assertRaises(self.driver.ForeignKeyViolationError):
            await self.conn.execute(
                "DELETE FROM public.bookings WHERE id=$1", booking_id)
        self.assertIsNotNone(await self.conn.fetchval(
            "SELECT id FROM public.bookings WHERE id=$1", booking_id))
        await self.conn.execute("DELETE FROM public.sms_logs WHERE id=$1", sms_id)
        await self.conn.execute("DELETE FROM public.bookings WHERE id=$1", booking_id)

        remaining_ids = [
            await self.conn.fetchval("""
                INSERT INTO public.users (username,password_hash)
                VALUES ('synthetic-user','synthetic-hash') RETURNING id
            """),
            await self.conn.fetchval("""
                INSERT INTO public.tenants (name,slug)
                VALUES ('Synthetic tenant','synthetic-tenant') RETURNING id
            """),
            await self.conn.fetchval("""
                INSERT INTO public.knowledge_articles (question,answer)
                VALUES ('Synthetic question?','Synthetic answer.') RETURNING id
            """),
            await self.conn.fetchval("""
                INSERT INTO public.analytics_events (event_type,event_data)
                VALUES ('synthetic-event','{"safe":true}'::jsonb) RETURNING id
            """),
            await self.conn.fetchval("""
                INSERT INTO public.api_usage (service_name)
                VALUES ('synthetic-service') RETURNING id
            """),
            await self.conn.fetchval(
                "INSERT INTO public.system_metrics DEFAULT VALUES RETURNING id"),
        ]
        generated_ids = [
            caller_id, call_log_id, appointment_id, *remaining_ids,
        ]
        self.assertTrue(all(isinstance(value, int) and value > 0 for value in generated_ids))
        with self.assertRaises(self.driver.UniqueViolationError):
            await self.conn.execute("""
                INSERT INTO public.api_usage (service_name)
                VALUES ('synthetic-service')
            """)
        self.assertEqual(await self.conn.fetchval(
            "SELECT count(*) FROM public.tenants"), 1)
        self.assertEqual(await self.conn.fetchval(
            "SELECT count(*) FROM public.admin_users"), 0)

    async def test_bootstrap_timestamp_trigger_updates_only_selected_row(self):
        await self.reset_public()
        await self.bootstrap()
        async with self.conn.transaction():
            first = await self.conn.fetchval("""
                INSERT INTO public.callers
                    (phone_number,name,first_call,last_call,created_at,updated_at)
                VALUES
                    ('+12025550121','First synthetic',
                     TIMESTAMPTZ '2000-01-01 00:00:00+00',
                     TIMESTAMPTZ '2000-01-01 00:00:00+00',
                     TIMESTAMPTZ '2000-01-01 00:00:00+00',
                     TIMESTAMPTZ '2000-01-01 00:00:00+00') RETURNING id
            """)
            second = await self.conn.fetchval("""
                INSERT INTO public.callers
                    (phone_number,name,first_call,last_call,created_at,updated_at)
                VALUES
                    ('+12025550122','Second synthetic',
                     TIMESTAMPTZ '2000-01-01 00:00:00+00',
                     TIMESTAMPTZ '2000-01-01 00:00:00+00',
                     TIMESTAMPTZ '2000-01-01 00:00:00+00',
                     TIMESTAMPTZ '2000-01-01 00:00:00+00') RETURNING id
            """)
        unrelated_before = await self.conn.fetchrow(
            "SELECT * FROM public.callers WHERE id=$1", second)

        async with self.conn.transaction():
            await self.conn.execute(
                "UPDATE public.callers SET name='Changed synthetic' WHERE id=$1", first)
        changed = await self.conn.fetchrow(
            "SELECT * FROM public.callers WHERE id=$1", first)
        unrelated_after = await self.conn.fetchrow(
            "SELECT * FROM public.callers WHERE id=$1", second)
        self.assertEqual(changed["name"], "Changed synthetic")
        self.assertGreater(changed["updated_at"], changed["created_at"])
        self.assertEqual(unrelated_after, unrelated_before)

    async def test_bootstrap_failure_rolls_back_every_object_then_retries(self):
        await self.reset_public()
        observed = {}

        class InjectedBootstrapFailure(Exception):
            pass

        try:
            async with self.conn.transaction():
                await self.conn.execute("SET LOCAL search_path = pg_catalog")
                await self.conn.execute(
                    BOOTSTRAP_SCHEMA_PATH.read_text(encoding="utf-8"))
                observed["tables"] = await self.conn.fetchval("""
                    SELECT count(*) FROM pg_catalog.pg_class
                    WHERE relnamespace='public'::pg_catalog.regnamespace
                      AND relkind='r'
                """)
                observed["sequences"] = await self.conn.fetchval("""
                    SELECT count(*) FROM pg_catalog.pg_class
                    WHERE relnamespace='public'::pg_catalog.regnamespace
                      AND relkind='S'
                """)
                observed["triggers"] = await self.conn.fetchval("""
                    SELECT count(*) FROM pg_catalog.pg_trigger t
                    JOIN pg_catalog.pg_class c ON c.oid=t.tgrelid
                    WHERE c.relnamespace='public'::pg_catalog.regnamespace
                      AND NOT t.tgisinternal
                """)
                observed["injected"] = True
                raise InjectedBootstrapFailure
        except InjectedBootstrapFailure:
            pass

        # These assertions sit outside the exception boundary, matching the
        # accepted T005-A rollback correction.
        self.assertEqual(observed, {
            "tables": 17, "sequences": 17, "triggers": 7, "injected": True,
        })
        self.assertEqual(await self.conn.fetchval("""
            SELECT count(*) FROM pg_catalog.pg_class
            WHERE relnamespace='public'::pg_catalog.regnamespace
              AND relkind IN ('r','S')
        """), 0)
        self.assertIsNone(await self.conn.fetchval(
            "SELECT pg_catalog.to_regprocedure("
            "'public.update_updated_at_column()')"))
        await self.bootstrap()
        self.assertEqual(await self.conn.fetchval("""
            SELECT count(*) FROM pg_catalog.pg_class
            WHERE relnamespace='public'::pg_catalog.regnamespace AND relkind='r'
        """), 17)

    async def test_bootstrap_conflict_preserves_original_and_no_partial_schema(self):
        await self.reset_public()
        await self.conn.execute(
            "CREATE TABLE public.calls (marker TEXT NOT NULL)")
        await self.conn.execute(
            "INSERT INTO public.calls (marker) VALUES ('preserve-me')")

        with self.assertRaises(self.driver.DuplicateTableError):
            async with self.conn.transaction():
                await self.conn.execute("SET LOCAL search_path = pg_catalog")
                await self.conn.execute(
                    BOOTSTRAP_SCHEMA_PATH.read_text(encoding="utf-8"))

        self.assertEqual(
            await self.conn.fetchval("SELECT marker FROM public.calls"),
            "preserve-me",
        )
        remaining = await self.conn.fetch("""
            SELECT relname,relkind::text FROM pg_catalog.pg_class
            WHERE relnamespace='public'::pg_catalog.regnamespace
              AND relkind IN ('r','S') ORDER BY relname
        """)
        self.assertEqual(
            [(row["relname"], row["relkind"]) for row in remaining],
            [("calls", "r")],
        )
        self.assertIsNone(await self.conn.fetchval(
            "SELECT pg_catalog.to_regprocedure("
            "'public.update_updated_at_column()')"))

    async def test_repair_preserves_history_and_supports_both_auth_updates(self):
        statements = auth_password_statements()
        self.assertEqual(len(statements), 2)
        for sql in statements:
            with self.assertRaises(self.driver.UndefinedColumnError):
                await self.conn.execute(sql, "synthetic-new-hash", 1)
        before = await self.snapshot()
        self.assertEqual(await self.migrate(False), "pending 0001")
        self.assertEqual(await self.snapshot(), before)
        self.assertEqual(await self.migrate(), "applied 0001")
        after = await self.snapshot()
        self.assertEqual(before["sequences"], after["sequences"])
        self.assertEqual(before["rows"]["bookings"], after["rows"]["bookings"])
        self.assertEqual(len(after["rows"]["bookings"]), 16)
        self.assertEqual(before["rows"]["admin_sessions"], after["rows"]["admin_sessions"])
        old = [json.loads(r["row"]) for r in before["rows"]["admin_users"]]
        new = [json.loads(r["row"]) for r in after["rows"]["admin_users"]]
        self.assertEqual(new, [dict(r, updated_at=None) for r in old])
        self.assertEqual(await self.migrate(), "up-to-date 0001")
        self.assertEqual(await self.migrate(False), "up-to-date 0001")
        self.assertEqual(await self.snapshot(), after)
        ledger = await self.conn.fetch("SELECT * FROM public.schema_migrations")
        self.assertEqual(len(ledger), 1)
        self.assertEqual(ledger[0]["version"], "0001")
        self.assertEqual(ledger[0]["checksum"], hashlib.sha256(
            (ROOT / "migrations/0001_admin_users_updated_at.sql").read_bytes()).hexdigest())
        self.assertIsNotNone(ledger[0]["applied_at"].tzinfo)
        for selected, sql in enumerate(statements, 1):
            unchanged = await self.conn.fetchrow("SELECT * FROM admin_users WHERE id=$1", 3-selected)
            self.assertEqual(await self.conn.execute(sql, "synthetic-new-hash", selected), "UPDATE 1")
            updated = await self.conn.fetchrow("SELECT * FROM admin_users WHERE id=$1", selected)
            self.assertEqual(updated["password_hash"], "synthetic-new-hash")
            self.assertIsNotNone(updated["updated_at"])
            self.assertEqual(await self.conn.fetchrow(
                "SELECT * FROM admin_users WHERE id=$1", 3-selected), unchanged)
        self.assertIsNotNone(await self.conn.fetchval("""
            INSERT INTO admin_users (username,email,password_hash)
            VALUES ('synthetic_new','new@example.invalid','synthetic-hash') RETURNING updated_at
        """))

    async def test_compatible_adoption_preserves_values_and_default(self):
        for default in ("", " DEFAULT NOW()", " DEFAULT CURRENT_TIMESTAMP"):
            with self.subTest(default=default):
                await self.conn.execute("DROP SCHEMA public CASCADE; CREATE SCHEMA public;")
                await self.conn.execute(PREDECESSOR)
                await self.conn.execute("ALTER TABLE admin_users ADD updated_at TIMESTAMP" + default)
                await self.conn.execute(
                    "UPDATE admin_users SET updated_at='2020-11-01 01:30:00' WHERE id=1")
                before = await self.snapshot()
                self.assertEqual(await self.migrate(), "applied 0001")
                after = await self.snapshot()
                for key in before["rows"]:
                    self.assertEqual(before["rows"][key], after["rows"][key])
                self.assertEqual(before["sequences"], after["sequences"])
                self.assertEqual([r for r in before["schema"] if r["relname"] == "admin_users"],
                                 [r for r in after["schema"] if r["relname"] == "admin_users"])
                self.assertEqual(await self.migrate(), "up-to-date 0001")
                self.assertEqual(await self.snapshot(), after)

    async def test_unrecognized_predecessors_fail_without_mutation(self):
        cases = [
            "DROP TABLE admin_users CASCADE",
            "ALTER TABLE admin_users ALTER username TYPE TEXT",
            "ALTER TABLE admin_users ALTER is_active SET NOT NULL",
            "ALTER TABLE admin_users DROP CONSTRAINT admin_users_email_key",
            "ALTER TABLE admin_users DROP CONSTRAINT admin_users_username_key; "
            "ALTER TABLE admin_users ADD UNIQUE(username,email)",
            "ALTER TABLE admin_users DROP CONSTRAINT admin_users_pkey CASCADE",
            "ALTER TABLE admin_users ADD unknown_column TEXT",
            "ALTER TABLE admin_users ADD updated_at TIMESTAMPTZ",
            "ALTER TABLE admin_users ADD updated_at TIMESTAMP NOT NULL DEFAULT NOW()",
            "ALTER TABLE admin_users ADD updated_at TIMESTAMP DEFAULT clock_timestamp()",
            "ALTER TABLE admin_users ADD updated_at TIMESTAMP DEFAULT '2001-01-01'",
            "CREATE FUNCTION public.now() RETURNS timestamp LANGUAGE SQL AS "
            "$$ SELECT TIMESTAMP '2001-01-01' $$; "
            "ALTER TABLE admin_users ADD updated_at TIMESTAMP DEFAULT public.now()",
            "CREATE FUNCTION public.t005_trigger() RETURNS trigger LANGUAGE plpgsql AS "
            "$$ BEGIN RETURN NEW; END $$; CREATE TRIGGER t005_unexpected BEFORE UPDATE "
            "ON admin_users FOR EACH ROW EXECUTE FUNCTION public.t005_trigger()",
            "ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY",
            "CREATE TABLE schema_migrations (version TEXT)",
            LEDGER + "ALTER TABLE schema_migrations ADD extra TEXT",
            LEDGER + "ALTER TABLE schema_migrations ALTER applied_at DROP NOT NULL",
            LEDGER + "ALTER TABLE schema_migrations ALTER applied_at TYPE TIMESTAMP",
            LEDGER + "ALTER TABLE schema_migrations ALTER version SET DEFAULT '0001'",
            LEDGER + "INSERT INTO schema_migrations VALUES ('unknown','x',NOW())",
            LEDGER + "INSERT INTO schema_migrations VALUES ('0001','wrong',NOW())",
        ]
        for case_number, sql in enumerate(cases):
            with self.subTest(case=case_number):
                await self.conn.execute("DROP SCHEMA public CASCADE; CREATE SCHEMA public;")
                await self.conn.execute(PREDECESSOR)
                await self.conn.execute(sql)
                before = await self.snapshot()
                for apply in (False, True):
                    with self.assertRaises(self.runner.MigrationError):
                        await self.migrate(apply)
                    self.assertEqual(await self.snapshot(), before)

    async def test_recorded_revision_checks_target_drift_and_checksum(self):
        for sql, category in (
            ("ALTER TABLE admin_users DROP updated_at", "incompatible schema"),
            ("ALTER TABLE admin_users ALTER updated_at TYPE TIMESTAMPTZ", "incompatible schema"),
            ("ALTER TABLE admin_users ALTER updated_at SET DEFAULT clock_timestamp()", "incompatible schema"),
            ("UPDATE schema_migrations SET checksum='drift'", "checksum drift"),
            ("UPDATE schema_migrations SET version='unknown'", "unknown version"),
        ):
            with self.subTest(category=category, sql=sql):
                await self.conn.execute("DROP SCHEMA public CASCADE; CREATE SCHEMA public;")
                await self.conn.execute(PREDECESSOR)
                await self.migrate()
                await self.conn.execute(sql)
                before = await self.snapshot()
                for apply in (False, True):
                    with self.assertRaisesRegex(self.runner.MigrationError, category):
                        await self.migrate(apply)
                    self.assertEqual(await self.snapshot(), before)

    async def test_concurrent_runners_and_status_without_advisory_lock(self):
        before = await self.snapshot()
        async with self.conn.transaction():
            self.assertTrue(await self.conn.fetchval(
                "SELECT pg_try_advisory_xact_lock($1::bigint)", self.runner.LOCK_KEY))
            self.assertEqual(await self.migrate(False), "pending 0001")
            with self.assertRaisesRegex(self.runner.MigrationError, "busy"):
                await self.migrate()
        self.assertEqual(await self.snapshot(), before)
        with mock.patch.dict(os.environ, {"MIGRATION_DATABASE_URL": self.dsn}):
            results = await asyncio.gather(self.runner.run(apply=True),
                                           self.runner.run(apply=True), return_exceptions=True)
        self.assertEqual(results.count("applied 0001"), 1)
        for result in results:
            self.assertTrue(result in ("applied 0001", "up-to-date 0001") or
                            isinstance(result, self.runner.MigrationError) and str(result) == "busy")
        self.assertEqual(await self.conn.fetchval("SELECT count(*) FROM schema_migrations"), 1)
        self.assertEqual(await self.migrate(), "up-to-date 0001")

    async def test_table_lock_timeout_has_no_partial_changes_and_allows_retry(self):
        before = await self.snapshot()
        started = time.monotonic()
        async with self.conn.transaction():
            await self.conn.execute("LOCK TABLE admin_users IN ACCESS EXCLUSIVE MODE")
            with self.assertRaisesRegex(self.runner.MigrationError, "busy"):
                await self.migrate()
        self.assertLess(time.monotonic() - started, 15)
        self.assertEqual(await self.snapshot(), before)
        self.assertEqual(await self.migrate(), "applied 0001")

    async def test_failure_after_ddl_rolls_back_and_releases_lock(self):
        before = await self.snapshot()
        observed = {}

        async def fail(conn, version, checksum):
            observed["column_exists"] = await conn.fetchval("""
                SELECT 1 FROM pg_attribute WHERE attrelid='public.admin_users'::regclass
                AND attname='updated_at' AND NOT attisdropped
            """)
            observed["ledger_rows"] = await conn.fetchval(
                "SELECT count(*) FROM public.schema_migrations")
            observed["injected"] = True
            raise RuntimeError(SENTINEL)

        with mock.patch.object(self.runner, "_record_revision", side_effect=fail):
            with self.assertRaises(self.runner.MigrationError) as raised:
                await self.migrate()
        # Assertions outside the runner cannot be swallowed by its error boundary.
        self.assertEqual(observed, {"column_exists": 1, "ledger_rows": 0, "injected": True})
        self.assertNotIn(SENTINEL, str(raised.exception))
        self.assertEqual(await self.snapshot(), before)
        self.assertEqual(await self.migrate(), "applied 0001")


if __name__ == "__main__":
    unittest.main()
